name = "cf-tg-web"
main = "./cf-worker-example.js"
compatibility_date = "2024-11-01"
workers_dev = true

# D1 binding for CF Builds / wrangler deploy
[[d1_databases]]
binding = "DB"
database_name = "tg-cf-web"
database_id = "34bc88ea-5115-4251-b036-a9ebb9e64000"
